name: simple
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.0.15
  overlay_support:
  flutter_spinkit:
  flutter_svg:
  cached_network_image:
  intl:
  provider: ^6.0.5
  dio: ^5.1.1
  qr_flutter: ^4.0.0
  another_imin_printer: ^0.6.0
  print_bluetooth_thermal: ^1.0.8
  esc_pos_utils_plus: ^2.0.1+6
  flutter_esc_pos_network: ^1.0.3
  image: ^4.0.17
  connectivity_plus: ^6.1.5
  internet_connection_checker: ^1.0.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  internet_connection_checker_plus: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter_icons:
  android: true
  ios: false
  image_path: "assets/image/koorai_logo.png"
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  #flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/image/


  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
